spring:
  application:
    name: eureka-service

server:
  port: 2001

eureka:
  server:
    enable-self-preservation: false
    #eureka 的自我保护状态：心跳失败的比例，在15分钟内是否低于85%,
    #如果出现了低于的情况，Eureka Server会将当前的实例注册信息保护起来，
    #同时提示一个警告，一旦进入保护模式，Eureka Server将会尝试保护其服务注册表中的信息，
    #不再删除服务注册表中的数据。也就是不会注销任何微服务
  instance:
    hostname: eureka1 #eureka 集群服务器之间，通过 hostname 来区分
    lease-renewal-interval-in-seconds: 30
    #最后一次心跳后，间隔多久认定微服务不可用，默认90
  client:
    register-with-eureka: true #profile的配置会覆盖公用配置
    fetch-registry: true #profile的配置会覆盖公用配置
    service-url:
      defaultZone: http://127.0.0.1:2002/eureka  #eureka1启动时向eureka2注册
